robots/urls.py
from django.conf.urls.defaults import *
from robots.views import rules_list

urlpatterns = patterns('',
    url(r'^$', rules_list, name='robots_rule_list'),
)

trivias/urls.py
from django.conf.urls.defaults import *
from trivias.feeds import LatestTriviasFeed

urlpatterns = patterns('',
    url(r'^$', 'trivias.views.show_latest', name='trivia-latest'),    
    url(r'^mytrivias/$', 'trivias.views.mytrivias', name='trivia-mytrivias'),
    url(r'^read/(?P<id>.+)/(?P<slug>[a-zA-Z0-9_.-]+)/$', 'trivias.views.read_more', name='trivia-read'),
    url(r'^edit/(?P<id>.+)/$', 'trivias.views.show_edit_form', name='trivia-edit'),
    url(r'^delete/(?P<id>.+)/$', 'trivias.views.delete_trivia', name='trivia-delete'),
    url(r'^add/$', 'trivias.views.add_trivia', name='trivia-add'),
    url(r'^update/$', 'trivias.views.update_trivia', name='trivia-update'),
    url(r'^by/(?P<slug>[a-zA-Z0-9_.-]+)/$', 'trivias.views.by_tag', name='trivia-by-tag'),
    url(r'^search/$', 'trivias.views.simple_search', name='trivia-simple-search'),
    url(r'^rate/(?P<id>.+)/$', 'trivias.views.rate_trivia', name='trivia-rate'),
    url(r'^bookmark/(?P<id>.+)/$', 'trivias.views.bookmark_trivia', name='trivia-bookmark'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from trivias.sitemaps import LatestTriviasSitemap

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {'trivias': LatestTriviasSitemap}}),
    url(r'robots\.txt$', include('robots.urls')),
#    url(r'^$', 'zhishi.views.show_latest'),
#    url(r'^zhishi/', include('zhishi.urls')),
    url(r'^$', 'trivias.views.show_latest'),
    url(r'^trivias/', include('trivias.urls')),
    url(r'^feedback/', include('feedback.urls')),
)


from django.conf import settings
if settings.LOCAL:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT}),
    )

trivias/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.db.models import signals
from django.template.defaultfilters import slugify
from django.conf import settings

from middleware import threadlocals

from tagging.fields import TagField
from tagging.models import Tag

class Category(models.Model):
    name = models.CharField(max_length=50)
    create_date = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return self.name


class Trivia(models.Model):
    author = models.ForeignKey(User, editable=False, default=threadlocals.get_current_user) 
    title = models.CharField(max_length=50)
    slug_title = models.SlugField(max_length=150, blank=True, null=True)
    body = models.TextField()
    pub_date = models.DateField(auto_now_add=True)
    is_public = models.BooleanField(default=True)
    approved = models.BooleanField(default=False)
    enable_comments = models.BooleanField(default=True)
    hits = models.IntegerField(default=0)
    tags = TagField()
    is_deleted = models.BooleanField(default=False)
    category = models.ForeignKey(Category)
    
    class Meta:
        ordering = ('-id', '-pub_date',)
    
    def __unicode__(self):
        return self.title
        
    def get_absolute_url(self):
        return '/trivias/read/%d/%s' % (self.id, self.slug_title)
    
    def set_tags(self, tags):
        Tag.objects.update_tags(self, tags)

    def get_tags(self):
        return Tag.objects.get_for_object(self)    
    
    def deletetrivia(self):
        self.is_deleted = True
 
def tip_pre_save(signal, instance, sender, **kwargs):
    #if not instance.slug_title:
    slug = slugify(instance.title)
    new_slug = slug
    counter = 0

    while Trivia.objects.filter(slug_title=new_slug).exclude(id=instance.id).count() > 0:
        counter += 1
        new_slug = '%s-%d'%(slug, counter)

    instance.slug_title = new_slug
signals.pre_save.connect(tip_pre_save, sender=Trivia)
    

class Bookmark(models.Model):
    user = models.ForeignKey(User)
    trivia = models.ForeignKey(Trivia)
    mark_date = models.DateField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)
    
    def __unicode__(self):
        return u'%s by %s (bookmarked in %s)' % (self.trivia, self.user, self.mark_date)

    def delete_bookmark(self):
        self.is_deleted = True

class Rating(models.Model):
    user = models.ForeignKey(User)
    trivia = models.ForeignKey(Trivia)
    useful = models.BooleanField(default=True)
    
    def __unicode__(self):
        return u'%s' % self.useful
    
    def get_rating(self):
        if self.useful:
            return u'useful'
        return u'not useful'

trivias/forms.py
# -*- coding: utf-8 -*-
from django.forms.models import ModelForm
from django.forms import forms
from django.conf import settings
from django.forms.widgets import TextInput
from django.utils import simplejson
from django.utils.safestring import mark_safe
from django.forms.widgets import HiddenInput
from django.forms.fields import IntegerField
from django.core.mail import EmailMessage

from tagging.forms import TagField
from tagging.models import Tag
from trivias.models import Trivia 


class AutoCompleteTagInput(TextInput):
    
    class Media:
        css = {
            'all': ('%s/js/jquery/jquery.autocomplete.css' % settings.MEDIA_URL,)
        }
        js = (
            '%s/js/jquery.js' % settings.MEDIA_URL,
            '%s/js/jquery/lib/jquery.bgiframe.min.js' % settings.MEDIA_URL,
            '%s/js/jquery/lib/jquery.ajaxQueue.js' % settings.MEDIA_URL,
            '%s/js/jquery/jquery.autocomplete.js' % settings.MEDIA_URL
        )

    def render(self, name, value, attrs=None):
        output = super(AutoCompleteTagInput, self).render(name, value, attrs)
        #page_tags = Tag.objects.usage_for_model(Lancamento)
        page_tags = Tag.objects.all()
        tag_list = simplejson.dumps([tag.name for tag in page_tags],
                                    ensure_ascii=False)
        return output + mark_safe(u'''<script type="text/javascript">
            jQuery("#id_%s").autocomplete(%s, {
                width: 150,
                max: 10,
                highlight: false,
                multiple: true,
                multipleSeparator: ", ",
                scroll: true,
                scrollHeight: 300,
                matchContains: true,
                autoFill: true,
                });
            </script>''' % (name, tag_list))


class TriviaForm(ModelForm):
    id = IntegerField(required=False, widget=HiddenInput())
    tags = TagField(max_length=50, label='Tags', required=False, widget=AutoCompleteTagInput())
    
    class Meta:
        model = Trivia
        exclude = ['author', 'slug_title', 'pub_date', 'hits', 'approved']
        
    def __init__(self, *args, **kwargs):
        super(TriviaForm, self).__init__(*args, **kwargs)
        if self.instance.id:
            self.initial['tags'] = ' '.join([item.name for item in Tag.objects.get_for_object(self.instance)])
    
    def save(self, *args, **kwargs):        
        self.instance.approved = settings.APPROVE_NEW_TIPS_AUTOMATICALY
        super(TriviaForm, self).save(*args, **kwargs)
        
    #    from_email = settings.DEFAULT_FROM_EMAIL
    #    recipient_list = [mail_tuple[1] for mail_tuple in settings.ADMINS]
    #    
    #    subject = '[TIP] %s' % self.instance.slug_title
    #    message = "Author: %s \nE-mail: %s\n\n%s\n\n%s" % (self.instance.author, self.instance.author.email, self.instance.title, self.instance.body)
    #    mail = EmailMessage(subject, message, from_email, recipient_list)
    #    try:
    #        mail.send()
    #    except:
    #        pass

trivias/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.views.generic.simple import direct_to_template
from django.contrib.comments.views.comments import post_comment
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, get_list_or_404
from django.http import Http404

from tagging.models import Tag, TaggedItem
from trivias.forms import TriviaForm
from trivias.models import Trivia, Bookmark

        

def _show_trivias_latest_in_home(request, trivias=None, tag=None):
    if trivias is None:
        trivias = Trivia.objects.filter(is_public=True, approved=True, is_deleted=False)
    
    if not tag is None:
        trivias = TaggedItem.objects.get_by_model(trivias, tag)
    
    context = {'trivias': trivias, 'active_menu':'home'}
    return direct_to_template(request, 'index.html', context)
    

def show_latest(request):
    return _show_trivias_latest_in_home(request)


def by_tag(request, slug):
    try:
        tag = Tag.objects.get(slug=slug)
        return _show_trivias_latest_in_home(request, None, tag)
    except:
        raise Http404
        

def read_more(request, id, slug=None):
    trivia = get_object_or_404(Trivia, pk=id)
    
    if not trivia.author == request.user:
        trivia.hits += 1
        trivia.save()
    
    context = {'trivia': trivia, 'active_menu':'home'}
    try:
        rating = trivia.rating_set.get(user=request.user)
        context.update({'rating': rating})
    except:
        pass
        
    try:
        bookmark = trivia.bookmark_set.get(user=request.user)
        context.update({'bookmark': bookmark})
    except:
        pass
    
    return direct_to_template(request, 'read.html', context)


def simple_search(request):
    if 'text' in request.GET:
        text = request.GET['text']
        
        trivias = Trivia.objects.filter(Q(title__icontains=text) | Q(body__icontains=text))
        return _show_trivias_latest_in_home(request, trivias, None)
    
    return HttpResponseRedirect(reverse('trivia-latest'))


@login_required
def mytrivias(request, form=None):
    if form == None:
        form = TriviaForm()
    trivias = Trivia.objects.filter(author=request.user)
    bookmarked_trivias = Bookmark.objects.filter(user=request.user)
    
    context = {'trivias':trivias, 'bookmarked_trivias': bookmarked_trivias, 'form': form, 'active_menu':'myzhishi'}
    return direct_to_template(request, 'mytrivias.html', context)


@login_required
def add_trivia(request):
    if request.POST:
        form = TriviaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('trivia-mytrivias'))

    return direct_to_template(request, 'add.html', {'form':TriviaForm()})


@login_required
def delete_trivia(request, id):
    trivia = get_object_or_404(Trivia, id=id, author=request.user)
    trivia.deletetrivia()
    trivia.save()
    return HttpResponseRedirect(reverse('trivia-mytrivias'))


@login_required
def show_edit_form(request, id, slug=None):
    trivia = get_object_or_404(Trivia, id=id, author=request.user)
    context = {'form': ZhishiForm(instance=trivia ), 'active_menu':'myzhishi'}
    return direct_to_template(request, 'edit.html', context)


@login_required
def update_trivia(request):
    if request.POST:
        id = request.POST.get('id')
        trivia = get_object_or_404(Trivia, id=id, author=request.user)
        form = TriviaForm(request.POST, instance=trivia)
        try:
            form.save()
            return HttpResponseRedirect(reverse('trivia-mytrivias'))
        except:
            pass
            
    context = {'form':form , 'active_menu':'myzhishi'}
    return direct_to_template(request, 'edit.html', context)


@login_required
def rate_trivia(request, id):
    if 'score' in request.GET:
        is_useful = (request.GET.get('score') == 'up')
        trivia = get_object_or_404(Trivia, id=id)
        
        if not request.user == trivia.author:
            try:
                rating = trivia.rating_set.get(user=request.user)
                rating.useful = is_useful
                rating.save()
            except:
                rating = trivia.rating_set.create(user=request.user, useful=is_useful)
            
            try:
                if '/read/' in request.META['HTTP_REFERER']:
                    return HttpResponseRedirect(request.META['HTTP_REFERER'])
            except:
                pass
            
    return HttpResponseRedirect(reverse('trivia-mytrivias'))


@login_required
def bookmark_trivia(request, id):
    if 'action' in request.GET:
        trivia = get_object_or_404(Trivia, pk=id)
        
        if not request.user == trivia.author:
            action = request.GET.get('action')
            if action == 'add':
                bookmarked_trivia = trivia.bookmark_set.get_or_create(user=request.user)
                
            elif action == 'delete':
                try:
                    bookmarked_trivia = trivia.bookmark_set.get(user=request.user)
                    bookmarked_trivia.delete_bookmark()
                    bookmarked_trivia.save()
                except:
                    pass

            try:
                if '/read/' in request.META['HTTP_REFERER']:
                    return HttpResponseRedirect(request.META['HTTP_REFERER'])
            except:
                pass

    return HttpResponseRedirect(reverse('trivia-mytrivias'))

templates/web/trivias/add.html
{% extends 'base_site.html' %}

{% block main %}

<div class="info">
  <h1>New Trivia</h1>
</div>

<form id="formTriviaAdd" name="formTriviaAdd" action="{% url trivia-add %}" method="post" class="genericform">
    {% include 'form.html' %}
    
    <div>
        <input type="submit" value="New" class="button">
        <input type="button" value="Cancel" class="button" onclick="history.go(-1);">
    </div>

</form>

{% endblock %}

templates/web/trivias/edit.html
{% extends 'base_site.html' %}

{% block main %}

<div class="info">
  <h1>Edit Trivia</h1>
</div>

<form id="formTriviaEdit" name="formTriviaEdit" action="{% url trivia-update %}" method="post" class="genericform">
    {% include 'form.html' %}
    
    <div>
        <input type="submit" value="Save" class="button">
        <input type="button" value="Cancel" class="button" onclick="history.go(-1);">
    </div>

</form>

{% endblock %}

templates/web/trivias/form.html
{% csrf_token %} 

{{ form.id }}
<label class="title" for="id_title" accesskey="t">Title</label> {{ form.title }} <span class="errormessage">{{ form.title.errors }}</span>
<label class="title" for="id_body" accesskey="b">Tip</label> {{ form.body }} <span class="errormessage">{{ form.body.errors }}</span>
<label class="title" for="id_tags" accesskey="d">Tags</label> {{ form.tags }} <span class="errormessage">{{ form.tags.errors }}</span>
<label class="title" for="id_category" accesskey="c">Category</label> {{ form.category}} <span class="errormessage">{{ form.category.errors }}</span>
<label class="title" ></label>{{ form.is_public }}<label class="desc" for="id_is_public"> Is public?</label>
<label class="title" ></label>{{ form.enable_comments }}<label class="desc" for="id_enable_comments"> Enable comments?</label>
<p class="terms">Attention: Your tip may be rejected if it is considered improper or duplicate by Administrator.</p>

templates/web/trivias/index.html
{% extends "base_site.html" %}

{% block main %}

{% load truncate %}

{% if not trivias %}
<div id="error404">
    <img src="{{ MEDIA_URL }}css/images/sadpenguin.png" width="150" height="137" alt="Sad penguin"/>
    <p>Sorry, no knowledge found.</p>
</div>
{% endif %}

{% load pagination_tags %}
{% autopaginate trivias 10 %}

<script type="text/javascript" src="{{MEDIA_URL }}js/socialshare.js"> </script>
<script type="text/javascript" src="http://widget.renren.com/js/rrshare.js"></script>
{% for trivia in trivias %}
<div class="post"> 

   {% include 'post_title.html' %}

   <div class="post-body">
        {{ trivia.body|striptags|truncate:100|removetags:"div b span a p br table"|safe }}
   </div>

    {% if trivia.body|striptags|truncate:100|length > 100 %}
        <div class="post-footer reply">
            <a href="{{ trivia.get_absolute_url }}" class="button">keep reading...</a>
        </div>
    {% endif %}
</div>
{% endfor %}

{% paginate %}

<div class="clear"></div>


{% endblock %}

templates/web/trivias/mytrivias.html
{% extends 'base_site.html' %}

{% block main %}

{% load pagination_tags %}

{% autopaginate trivias 10 %}

<div class="tips">
    <div class="info"><h1>My Trivias</h1></div>

    {% if trivias %}
        {% paginate %}
        <table cellpadding="0" cellspacing="0" border="1">
            <thead>
                <td width="80">Posted in</td>
                <td width="400">Title</td>
                <td class="center">Hits</td>
                <td class="center">Approved?</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </thead>
            <tbody>
            {% for trivia in trivias %}
                <tr style="background:{% cycle '#ffffff' '#f8f8f8' %}">
                    <td>{{ trivia.pub_date }}</td>
                    <td><a href="{{ trivia.get_absolute_url }}">{{ trivia.title }}</a></td>
                    <td class="center">{{ trivia.hits }}</td>
                    <td class="center" style="color:{% if trivia.approved %}green{% else %}red{% endif %}">{{ trivia.approved|yesno }}</td>
                    <td><a href="{% url trivia-edit trivia.id %}" title="Edit"><div class="edit"></div><noscript>Edit</noscript></a></td>
                    <td><a href="{% url trivia-delete trivia.id %}" title="Delete"><div class="delete"></div><noscript>Delete</noscript></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% else %}
        <p style="font-size:0.8em">No tips.</p>
    {% endif %}

</div>

<br><br>

{% autopaginate bookmarked_trivias 10 %}

<div class="tips">
    <div class="info"><h1>Bookmarked Trivias</h1></div>

    {% if bookmarked_trivias %}
        <table cellpadding="0" cellspacing="0" border="1">
            <thead>
                <td width="80">Posted in</td>
                <td width="400">Title</td>
                <td width="150" class="center">Author</td>
                <td>&nbsp;</td>
            </thead>
            <tbody>
            {% for b in bookmarked_trivias %}
                <tr style="background:{% cycle '#ffffff' '#f8f8f8' %}">
                    <td>{{ b.trivia.pub_date }}</td>
                    <td><a href="{{ b.trivia.get_absolute_url }}">{{ b.trivia.title }}</a></td>
                    <td class="center">{{ b.trivia.author }}</td>
                    <td><a href="{% url trivia-bookmark b.trivia.id %}?action=delete" title="Delete"><div class="delete"></div><noscript>Delete</noscript></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% paginate %}
        
    {% else %}
        <p style="font-size:0.8em">No bookmarked tips. You can't add on bookmark yourself tips.</p>
    {% endif %}

</div>

<br><br>

<div class="info">
  <h1>New Tip</h1>
  <div></div>
</div>

<form id="formTriviaAdd" name="formTriviaAdd" action="{% url trivia-add %}" method="post" class="genericform">
    {% include 'form.html' %}

    <div>
        <input type="submit" value="Add" class="button">
    </div>

</form>

{% endblock %}

templates/web/trivias/post_title.html
{% load truncate %}

<h1 class="post-title"><a href="{{ trivia.get_absolute_url }}" title="{{ trivia.title }}"><strong>{{ trivia.title|upper|truncate:47 }}</strong></a>

<span style="float:right"><a href="javascript:void(0);"  onclick="window.open('http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url='+encodeURIComponent('http://www.douzhr.com{{ trivia.get_absolute_url }}'));return false;" title="分享到QQ空间"><img src="http://qzonestyle.gtimg.cn/ac/qzone_v5/app/app_share/qz_logo.png" alt="分享到QQ空间" style="vertical-align:middle;padding-top:2px"/></a>

<a href="javascript:shareToQQ('{{trivia.get_absolute_url}}', '{{trivia.body}}')" title="腾讯微博分享"><img src="http://v.t.qq.com/share/images/s/weiboicon16.png"  alt="新浪微博分享" style="vertical-align:middle;padding-top:0px"></a>
<a href="javascript:shareToSina('{{trivia.get_absolute_url}}', '{{trivia.body}}')" title="新浪微博分享"><img src="http://t.sina.com.cn/favicon.ico"  alt="新浪微博分享" style="vertical-align:middle;padding-top:0px"></a>
<a href="javascript:shareToDouban('{{trivia.get_absolute_url}}', '{{trivia.title}}')" title="豆瓣分享"><img src="http://www.douban.com/favicon.ico"  alt="豆瓣分享" style="vertical-align:middle;padding-top:0px"></a>
<a href="javascript:shareToRenren('{{trivia.get_absolute_url}}', '{{trivia.title}}', '{{trivia.body|truncate:100|safe}}')" title="人人网分享"><img src="http://www.wtzy.net/tpl/red/img/renren.gif"  alt="人人网分享" style="vertical-align:middle;padding-top:0px"></a></span></h1>

<h2 class="post-header-line1">{{ trivia.pub_date|date:"F j, Y" }} by {{ trivia.author }} {% if trivia.get_tags %}| {{ trivia.get_tags|safeseq|join:", " }} {% endif %}</h2>

{% ifequal request.user trivia.author  %}
    <a href="{% url trivia-edit trivia.id %}" title="Edit"><div class="edit" style="float:left;margin-right:5px;"></div><noscript>Edit</noscript></a>
    <a href="{% url trivia-delete trivia.id %}" title="Delete"><div class="delete" style="float:left;"></div><noscript>Delete</noscript></a>
    <br/>
{% endifequal %}
<br/>

templates/web/trivias/read.html
{% extends 'base_site.html' %}

{% load comments %}
{% load gravatar %}

{% block meta_keywords %}{{ trivia.title }}{% endblock %}

{% block title %}
  {{ block.super }} - {{ trivia.title|lower }}
{% endblock %}

{% block main %}
<div class="post">
    {% include 'post_title.html' %}
    <div class="post-body">{{ trivia.body|striptags|linebreaksbr|safe }}</div>
</div>

<div style="width:640px">
    <span class="post-button">
        {% if bookmark %}
           It was <b>bookmarked</b>.
        {% else %}
            <a href="{% url trivia-bookmark trivia.id %}?action=add" class="common">Add</a> or 
        {% endif %}
        
        <a href="{% url trivia-bookmark trivia.id %}?action=delete" class="common">Delete</a> on bookmark.
  
        <br/>
        
        {% if rating %}
            You rating as <b>{{ rating.get_rating }}</b>.
            Rating as
            {% if rating.useful %}
                <a href="{% url trivia-rate  trivia.id %}?score=down" class="common">not useful</a>.
            {% else %}
                <a href="{% url trivia-rate trivia.id %}?score=up" class="common">useful</a>.
            {% endif %}
        {% else %}
            Rating as 
            <a href="{% url trivia-rate trivia.id %}?score=up" class="common">useful</a> or 
            <a href="{% url trivia-rate trivia.id %}?score=down" class="common">not useful</a>.
        {% endif %}
    </span>
</div>

<div class="clear"></div><br/>


<div id="comment-box">
    
    {% get_comment_count for trivia as comment_count %}
    <h3>{{ comment_count }} comment{{ comment_count|pluralize }}</h3>
    <ol class="commentlist">
        {% get_comment_list for trivia as comment_list %}
        {% for comment in comment_list %}
            <li class="comment even thread-even depth-{% cycle '1' '2' %}">
                <div class="comment-author vcard">
                    {% gravatar comment.user_email 48 %}
                    <cite class="fn">
                        <a class="url" href="{{ comment.url }}">{{ comment.name }}</a>
                    </cite>
                </div>
                <div class="comment-meta commentmetadata">
                    <span>{{ comment.submit_date|date:"F j, Y" }}</span>
                </div>
                <p>{{ comment.comment|linebreaks }}</p>
                <div class="reply" style="display:none">
                    <a class="comment-reply-link">Reply</a>
                </div>
            </li>
        {% endfor %}
    </ol>

    {% render_comment_form for trivia %}
</div>

{% endblock %}